name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Build
      run: echo Hello, world!
    - name: Run tests
      run: | 
        xcodebuild clean test -project action.xcodeproj -scheme action -destination "platform=iOS Simulator,name=iPhone 11"
